// Generated by IcedCoffeeScript 108.0.9
(function() {
  var b64_image, fs, log, mime, _,
    __slice = [].slice;

  log = function() {
    var x;
    x = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    try {
      return console.log.apply(console, x);
    } catch (_error) {}
  };

  _ = require('lodash');

  fs = require('fs');

  mime = require('mime');

  module.exports = b64_image = {
    convert: function(file) {
      var bulk;
      if (!fs.statSync(file)) {
        throw new Error("File does not exist");
      }
      bulk = fs.readFileSync(file).toString('base64');
      return 'data:' + require('mime').lookup(file) + ';base64,' + bulk;
    },
    run: function() {
      var cli;
      cli = process.argv.slice(2);
      if (!cli.length || cli.join(' ').match('help')) {
        log("Usage ./ <file>");
        process.exit(0);
      }
      log(this.convert(cli.shift()));
      return process.exit(0);
    }
  };

  if (process.env.TAKY_DEV) {
    log(/TAKY_DEV/);
    log(b64_image.convert(__dirname + '/test/google.png'));
  }

}).call(this);
